-- Tabla de instrucciones por tipo de culto y rol
CREATE TABLE IF NOT EXISTS public.instrucciones_culto (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  culto_type_id bigint NOT NULL REFERENCES public.culto_types(id) ON DELETE CASCADE,
  rol text NOT NULL CHECK (rol IN ('introduccion', 'ensenanza', 'testimonios', 'finalizacion')),
  titulo_es text NOT NULL DEFAULT '',
  titulo_ca text NOT NULL DEFAULT '',
  contenido_es text NOT NULL DEFAULT '',
  contenido_ca text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(culto_type_id, rol)
);

COMMENT ON TABLE public.instrucciones_culto IS 'Instrucciones por tipo de culto y rol (Intro, Enseñanza, Testimonios, Finalización)';

ALTER TABLE public.instrucciones_culto ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios autenticados pueden leer instrucciones"
  ON public.instrucciones_culto FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Solo service role puede escribir instrucciones"
  ON public.instrucciones_culto FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
